name: publish_libraries
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npx nx run-many -t build --parallel=3
      - run: node devel/publish_libs.js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}